spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

csv:
  read-on-startup: true
  folder:
    path: cryptosource

logging:
  level:
    root: INFO
    com.my.project.cryptoservice: DEBUG
    com.my.project.cryptoservice.service: DEBUG

cryptos:
  available: BTC,DOGE,ETH,LTC,XRP,ADA,ATOM